//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EscapeRoom.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EscapeRoom.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agent .
        /// </summary>
        internal static string agentNoun {
            get {
                return ResourceManager.GetString("agentNoun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to height.
        /// </summary>
        internal static string confirmRoomHeight {
            get {
                return ResourceManager.GetString("confirmRoomHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure with this size? [Y/n] .
        /// </summary>
        internal static string confirmRoomSizeMessage {
            get {
                return ResourceManager.GetString("confirmRoomSizeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to width.
        /// </summary>
        internal static string confirmRoomWidth {
            get {
                return ResourceManager.GetString("confirmRoomWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to )
        ///After then, the door (.
        /// </summary>
        internal static string controlsAfterDoor {
            get {
                return ResourceManager.GetString("controlsAfterDoor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ) will be visible and may be entered by heading to it.
        ///.
        /// </summary>
        internal static string controlsDoor {
            get {
                return ResourceManager.GetString("controlsDoor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  keys:
        /// ↑ To move up, use the W key\n ↓ To go down, use the S key
        /// ← To go left, use the A key
        /// → To go right, use the D key 
        ///You may collect it by wallking over the key card (.
        /// </summary>
        internal static string controlsKeys {
            get {
                return ResourceManager.GetString("controlsKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Before we begin the mission, I&apos;d want to provide you with a few advice. 
        ///You can move around by using the .
        /// </summary>
        internal static string introControls {
            get {
                return ResourceManager.GetString("introControls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , welcome aboard! We look forward to working with you. 
        ///
        ///Let&apos;s go back to business. According to our sources, SAE is planning a secret weapon that will pose a danger to our 
        ///President Joe Mama. One of our spies was dispatched to gather intel from the SAE&apos;s headquarters, but we lost contact 
        ///with him after a time. 
        ///
        ///Now it&apos;s your turn to track him down and figure out what&apos;s going on at their headquarters, but first we need an 
        ///estimate of the size of one of their buildings.
        ///.
        /// </summary>
        internal static string introEstimateRoom {
            get {
                return ResourceManager.GetString("introEstimateRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Mission:
        ///.
        /// </summary>
        internal static string mission {
            get {
                return ResourceManager.GetString("mission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ■ Escape from the HQ
        ///.
        /// </summary>
        internal static string objectiveEscape {
            get {
                return ResourceManager.GetString("objectiveEscape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ■ Collect the Keycard
        ///.
        /// </summary>
        internal static string objectiveKeycard {
            get {
                return ResourceManager.GetString("objectiveKeycard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to try again? [Y/n] .
        /// </summary>
        internal static string tryAgainPrompt {
            get {
                return ResourceManager.GetString("tryAgainPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the .
        /// </summary>
        internal static string verifyRoomEnter {
            get {
                return ResourceManager.GetString("verifyRoomEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  of the building (minimum 15 - maximum 230): .
        /// </summary>
        internal static string verifyRoomMinMax {
            get {
                return ResourceManager.GetString("verifyRoomMinMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W,A,S,D.
        /// </summary>
        internal static string WASD {
            get {
                return ResourceManager.GetString("WASD", resourceCulture);
            }
        }
    }
}
